### ISSUE TITLE
aidgent is ignoring subsequent messages

### ISSUE THREAD

**Issue by rawwerks** [aidgent/aidgent#11]
- make sure the events are triggered per issue comment 
- make sure the api key used is that of the commenter who mentioned aidgent, not the issue creator or a previous commenter.

**Comment by rawdummy** [comment]
@aidgent turn this issue into a new file text.txt

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by rawdummy** [comment]
@aidgent turn this issue into a new file text.txt

**Comment by aidgent** [comment]
You are almost set up! I can see that you signed up at [https://aidgent.ai](https://aidgent.ai). Now you just need to paste a valid OpenAI API Key into [https://aidgent.ai/account](https://aidgent.ai/account), click `Update`, and then `@aidgent` me again after you've done that. You can get an API Key at [https://platform.openai.com/](https://platform.openai.com/).

**Comment by aidgent** [comment]
You are almost set up! I can see that you signed up at [https://aidgent.ai](https://aidgent.ai). Now you just need to paste a valid OpenAI API Key into [https://aidgent.ai/account](https://aidgent.ai/account), click `Update`, and then `@aidgent` me again after you've done that. You can get an API Key at [https://platform.openai.com/](https://platform.openai.com/).

**Comment by aidgent** [comment]
You are almost set up! I can see that you signed up at [https://aidgent.ai](https://aidgent.ai). Now you just need to paste a valid OpenAI API Key into [https://aidgent.ai/account](https://aidgent.ai/account), click `Update`, and then `@aidgent` me again after you've done that. You can get an API Key at [https://platform.openai.com/](https://platform.openai.com/).

**Comment by aidgent** [comment]
You are almost set up! I can see that you signed up at [https://aidgent.ai](https://aidgent.ai). Now you just need to paste a valid OpenAI API Key into [https://aidgent.ai/account](https://aidgent.ai/account), click `Update`, and then `@aidgent` me again after you've done that. You can get an API Key at [https://platform.openai.com/](https://platform.openai.com/).
