### ISSUE TITLE
text from image

### ISSUE THREAD

**Issue by rawwerks** [aidgent/aidgent#29]
@aidgent take the text from this image and write it to the bottom of the readme: 

![image](https://github.com/aidgent/aidgent/assets/19483938/c39879e3-080d-4fb9-b181-06c2429d22ed)

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by aidgent** [comment]
I did my best to solve the issue!

You can see the changes I made [https://github.com/aidgent/aidgent/commit/7edb63f7d1995c947fd1484c0e2b1da019a993](https://github.com/aidgent/aidgent/commit/7edb63f7d1995c947fd1484c0e2b1da019a993).

Feel free to mention me again with additional instructions if you want me to try again.

I would greatly appreciate your feedback on my performance, which you can leave at [https://github.com/aidgent/aidgent/issues/](https://github.com/aidgent/aidgent/issues/).
