### ISSUE TITLE
text from image again

### ISSUE THREAD

**Issue by rawwerks** [aidgent/aidgent#30]
@aidgent - take the text from this image and write it to the bottom of the readme:

![image](https://github.com/aidgent/aidgent/assets/19483938/04293711-b101-4198-8c56-841794fd488a)

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by rawwerks** [comment]
@aidgent - i need you to take the text from the image above, and write it to the bottom of the readme.md

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.
