### ISSUE TITLE
image text

### ISSUE THREAD

**Issue by rawwerks** [aidgent/aidgent#31]
@aidgent - write the text from this image to the bottom of readme.md

![image](https://github.com/aidgent/aidgent/assets/19483938/55eb102f-e9c2-4042-a4cd-4012ad963961)

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by rawwerks** [comment]
@aidgent - write the text from the image above to the bottom of readme.md

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by rawwerks** [comment]
@aidgent - write the text from the image above to the bottom of readme.md

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.
