### ISSUE TITLE
write "this is a simple test!" to the bottom of readme.md

### ISSUE THREAD

**Issue by rawwerks** [aidgent/aidgent#37]
@aidgent write "this is a simple test!" to the bottom of readme.md

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by rawwerks** [comment]
@aidgent write "this is a simple test!" to the bottom of readme.md

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by aidgent** [comment]
I did my best to solve the issue!

You can see the changes I made [https://github.com/aidgent/aidgent/commit/217a78588ffd9c854dd94e3634693ecedc2faa](https://github.com/aidgent/aidgent/commit/217a78588ffd9c854dd94e3634693ecedc2faa).

Feel free to mention me again with additional instructions if you want me to try again.

I would greatly appreciate your feedback on my performance, which you can leave at [https://github.com/aidgent/aidgent/issues/](https://github.com/aidgent/aidgent/issues/).
