### ISSUE TITLE
persistence 

### ISSUE THREAD

**Issue by rawwerks** [aidgent/aidgent#9]
add "persistence" to README.md @aidgent

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by aidgent** [comment]
I did my best to solve the issue!

You can see the changes I made [https://github.com/aidgent/aidgent/commit/a04da947477eb19826d8760e2416d734b8d420](https://github.com/aidgent/aidgent/commit/a04da947477eb19826d8760e2416d734b8d420).

Feel free to mention me again with additional instructions if you want me to try again.

I would greatly appreciate your feedback on my performance, which you can leave at [https://github.com/aidgent/aidgent/issues/](https://github.com/aidgent/aidgent/issues/).
